### ISSUE TITLE
Gas charged before revert call is being reverted

### ISSUE THREAD

**Issue by lrettig** [ewasm/hera#120]
The [`revert`](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-140.md) operation should halt the executing contract without consuming all remaining gas. However, gas that has already been spent before calling `revert` should not be refunded.

When testing I noticed that if I insert a `useGas` call before calling `revert`, that gas is actually not subtracted from the final state.

**Comment by axic** [comment]
Is this still an issue @lrettig ?

**Comment by lrettig** [comment]
I'll test again asap. To be clear, https://github.com/ethereum/cpp-ethereum/pull/4909 is _not_ intended to fix this issue right?

**Comment by axic** [comment]
No, the description of this case suggest something is totally broken :)

**Comment by lrettig** [comment]
Confirmed that this is not currently an issue
