### ISSUE TITLE
Code after revert is being executed

### ISSUE THREAD

**Issue by lrettig** [ewasm/hera#121]
The [`revert`](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-140.md) operation should immediately halt execution of a contract, and no code after the `revert` code should run. However, in testing I found that code following a `revert` call is in fact being called (I tested using `useGas` to cause the executing contract to run out of gas).

**Comment by axic** [comment]
Note, according to the design it doesn't stop execution: https://github.com/ewasm/design/blob/master/eth_interface.md#revert

**Comment by lrettig** [comment]
Got it, sounds like this is expected behavior. I'll close this.
