### ISSUE TITLE
CREATE doesn't work

### ISSUE THREAD

**Issue by jwasinger** [ewasm/hera#122]
See this branch with the test case in order to reproduce: https://github.com/ewasm/tests/tree/create-test

This is all the output I get:

```
Executing...
useGas 300
create0 14 0 132
```

**Comment by axic** [comment]
What is the return value of `create` (it is `i32`)?

**Comment by jakelang** [comment]
@jwasinger please try out the create-fix branch.

**Comment by jwasinger** [comment]
Updated the test case.  I am getting back a code of `0x02`: revert.

**Comment by jakelang** [comment]
Well, at least we know that works :smile: 
Looking into the cause of the problem, now that we know it is failing correctly.

**Comment by axic** [comment]
I think this has been fixed with https://github.com/ethereum/cpp-ethereum/pull/4888

**Comment by axic** [comment]
ping @jwasinger

**Comment by axic** [comment]
Probably this is the same underlying problem as #129.
