### ISSUE TITLE
Call with no data, no value, does nothing

### ISSUE THREAD

**Issue by jwasinger** [ewasm/hera#126]
See the test case:  https://github.com/ewasm/tests/tree/call-no-data-value .  The issue is that none of the code in the called account executes.

```
Test Case "stEWASMTests":
100%
Executing...
useGas 270
$call 30d40 0 0 0 0
storageStore c8 64
/home/jwasinger/projects/cpp-ethereum/test/tools/libtesteth/ImportTest.cpp(510): error: in "GeneralStateTests/stEWASMTests": callNoDataNoValue Check State: deadbeef00000000000000000000000000000001: incorrect storage [0x] = 0x, expected [0x] = 0x01
Byzantium data: 0 gas: 0 val: 0
```

**Comment by jwasinger** [comment]
Note to self:  un-zero the memory before it is stored...  so we can tell whether call is erring or not executing

**Comment by axic** [comment]
Make sure it is not 0, 1 or 2 :)

**Comment by jwasinger** [comment]
Yup.  It is indeed 0

**Comment by axic** [comment]
@jwasinger is this still a problem?

**Comment by jwasinger** [comment]
Test is passing now.
