### ISSUE TITLE
Hera should roll back the effects of a transaction when it enters an exceptional state

### ISSUE THREAD

**Issue by jwasinger** [ewasm/hera#136]
As I am writing new contracts (which cause hera/cpp-ethereum to crash), I am seeing that some of the effects of the transaction where an exception is triggered (*not* an EVM exception) are not rolled back.

For example, the nonce is incremented but not reset upon crash.  I will try to post an example in this issue.

**Comment by axic** [comment]
@chfast do you think such issues could happen in cpp-eth?

**Comment by chfast** [comment]
By the exception you mean something like `heraAssert()` failing?

If `heraAssert()` exits, this is not problem.
The best solution would be return `EVM_INTERNAL_ERROR` as the status code. If you need more status codes, let me know. I had an idea how to do it, without modifying EVM-C, but it was never used in practice.

**Comment by axic** [comment]
Is this still a problem?
