### ISSUE TITLE
Build Hera as a shared library

### ISSUE THREAD

**Issue by chfast** [ewasm/hera#159]
The cmake config for this should be `cmake -DBUILD_SHARED_LIBS=ON`.

We need a new toolchain file with `set(CMAKE_POSITION_INDEPENDENT_CODE ON)`. Let's call it `cxx11-pic.cmake` following Hunter/polly convention. This toolchain file should be selected when `BUILD_SHARED_LIBS` is on.

Also add a CI build of shared lib.

I started to extract these common CMake patterns in https://github.com/ethereum/cable (currently used in 2 other projects). We can also consider using it.

**Comment by axic** [comment]
@chfast are you doing this now?
