### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by axic** [ewasm/hera#178]
Hera currently is distributed under the MIT license, which I really like being so liberal and simple, however Apache 2.0 or MPL 2.0 for their explicit requirements around patents may be beneficial.

Would such a license change be useful? If so, which license is preferred?

cc @jakelang, @chfast, @jwasinger, @lrettig, @esteve, @cdetrio, @hugo-dc and @GreatAttractor

**Comment by jakelang** [comment]
Might make sense to switch to Apache 2 if we want to have the protections against the patent system while still being permissively licensed. MPL is a step further in the direction of copyleft so we should discuss further if we want to consider that.

**Comment by esteve** [comment]
I'd go with Apache (disclaimer: I'm a member of the Apache Software Foundation, so I'm biased). Not only it contains certain protections against being sued for patent infringement, but it'd also prevent anyone from using the same trademarks and names, and require any derived code based on Hera's to state their changes. Also, if a NOTICE file is added in Hera's repo, it'll have to be included in any derived work.

**Comment by axic** [comment]
Is anyone against moving to Apache 2.0?

**Comment by jwasinger** [comment]
I vote for moving to Apache 2.0 (@axic answer your gitter/discord DMs :) )

**Comment by lrettig** [comment]
Isn't there someone from EF who should weigh in on this? Is there no standard for EF-affiliated repositories?

**Comment by axic** [comment]
We have external contributors on this repo who need to agree to the license change.

**Comment by hugo-dc** [comment]
I'm ok with moving to Apache 2.0

**Comment by cdetrio** [comment]
Apache 2.0 and MPL are both fine with me.
