### ISSUE TITLE
Value exceeds 64 bits

### ISSUE THREAD

**Issue by hugo-dc** [ewasm/hera#190]
I wrote a [new test case](https://github.com/ewasm/tests/blob/test-low-balance/src/GeneralStateTestsFiller/stEWASMTests/callNotEnoughBalanceFiller.yml) in order to validate that we get an OOG exception when there is a call sending a value and the value is higher than the current sender Balance. Instead the result is the following:

```
100%
Executing...
importGlobals
DEBUG printMemHex(0x14:0x20): 20 a1 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
InternalError: Value exceeds 64 bits.
Executing...
importGlobals
DEBUG printMemHex(0x14:0x20): 20 a1 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
InternalError: Value exceeds 64 bits.
```

https://github.com/ewasm/hera/blob/1a219f0b5ebeaebbbb13639793d476f3fee6bf50/src/eei.cpp#L875

Here it is comparint the balance and value, both are u128 and it is being validated by a function that validates 64 bit numbers.

**Comment by axic** [comment]
This is also an endianess issue.

**Comment by axic** [comment]
Also there should be test cases for using > 64 bit values.

**Comment by jwasinger** [comment]
Related: https://github.com/ewasm/evm2wasm/issues/219

**Comment by axic** [comment]
The other problem here is that `ensureSenderBalance` is just broken, because it uses `safeLoadUin128`, which truncates the value into `uin64_t`. 

`ensureSenderBalance` should be rewritten to properly handle the values.
