### ISSUE TITLE
Memory copying should write zeros for bytes that are out of bounds in the source location

### ISSUE THREAD

**Issue by jwasinger** [ewasm/hera#221]
See this trace of randomStatetest283 from evm2wasm:
https://gist.github.com/jwasinger/f85a735066491d56f52513a1cffddeeb

**Comment by jwasinger** [comment]
https://github.com/ewasm/hera/pull/222

**Comment by lrettig** [comment]
Looks like this is no longer an issue per https://github.com/ewasm/hera/pull/222#issuecomment-390824463, also https://github.com/ewasm/tests/issues/34 and https://github.com/ewasm/evm2wasm/issues/250. Can we close this?
