### ISSUE TITLE
First few bytes of code in dynamic CREATE is being overwritten

### ISSUE THREAD

**Issue by lrettig** [ewasm/hera#246]
CC @axic 

Test: https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stCallCodes/callcodeDynamicCodeFiller.json
Reference trace: https://gist.github.com/lrettig/17e00c2847d9ca13781aa5c6ff1d2d83
Hera trace (including a bunch of new debug output): https://gist.github.com/lrettig/89bd77db5091e943eb98d31ac612c405

Note that I already fixed one issue here (haven't PRed yet): https://github.com/lrettig/hera/commit/52c3c9e77688b74d447859399f47df2459262011

The dynamic code is still correct here: https://github.com/ewasm/hera/blob/501406933c64cd8ffe3c5bd2560b84b677d1228b/src/eei.cpp#L809

And it's screwed up here: https://github.com/ethereum/cpp-ethereum/blob/c14ccdbb35681b572b1102958ef9bfd58a1f003e/libethereum/Executive.cpp#L364

**Comment by axic** [comment]
Even though there is a native test for the interface, it seems it is only creating a 0 byte account: https://github.com/ewasm/tests/blob/wasm-tests/src/GeneralStateTestsFiller/stEWASMTests/createFiller.yml

There is a need for a proper creation test.

**Comment by lrettig** [comment]
Thanks for spotting this @axic, will work on it here: https://github.com/ewasm/tests/issues/39
