### ISSUE TITLE
Add commandline option to load bytecode for system contracts

### ISSUE THREAD

**Issue by axic** [ewasm/hera#288]
Proposed syntax:
- `sys:<address>=<path>`
- `sys:sentinel=<path>` (alias to 0x00...00e?)
- `sys:evm2wasm=<path>` (likewise)

For example, one would run `testeth -t GeneralStateTests/stExample -- --testpath ~/tests --singlenet "Byzantium" --singletest "add11" --vm ~/libhera.so --evmc sys:evm2wasm=my_cool_version_of_evm2wasm.wasm`

`sys` stands for system contract, while the `address` can be any ethereum address (hex encoded, all nibbles set, with the `0x` prefix) and `path` is a relative filesystem path to load the binary from.

Additionally `sentinel` and `evm2wasm` are an aliases for their respective addresses.

The main benefit here is that we can load system contracts without adjusting the genesis and as a result makes testing way easier.

In the future we could think about migrating all these settings over to a configuration file.

**Comment by jakelang** [comment]
@axic Figured as much. Should this be considered blocked on the evmc issue or should it be implemented the dirty way?

**Comment by axic** [comment]
It should only do case 1: replace the code hera has for the given account, but it is up to the client to actually route the call to hera.
