### ISSUE TITLE
Clarify endianness of memory access operations

### ISSUE THREAD

**Issue by jakelang** [ewasm/hera#318]
It has become a bit confusing that the overloaded functions for memory access actually have different functionality, in that some automatically convert endianness and some do not.

**Comment by axic** [comment]
So basically Hera considers both 128, 160 and 256bit values and numbers and does byteswapping on them.

However, only 128-bit should be a number given that refers to "Ether value", while 160-bit values represent addresses and 256-bit values represent storage keys, values and log data.
