### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by jwasinger** [ewasm/hera#330]
I'm trying to build Hera: https://github.com/jwasinger/go-ethereum/blob/evmc-docker/Dockerfile

Getting the following error:
```
[ 33%] Linking C static library libevmc-instructions.a
CMake Error at cmake/cable/buildinfo/buildinfo.cmake:8 (string):
  string no output variable specified


make[2]: *** [hera/buildinfo.c] Error 1
```

**Comment by axic** [comment]
I think #320 fixed this.

**Comment by chfast** [comment]
For now explicitly specify the build type `-DCMAKE_BUILD_TYPE=Release`.
