### ISSUE TITLE
Fuzzing Hera

### ISSUE THREAD

**Issue by axic** [ewasm/hera#376]
It should be fuzzed with random inputs to be executed (with and without the sentinel).

Most of the fuzzing corpus should be built with the successful test cases of ewasm tests suite. Goal is fuzzing the EEI implementation.

**Comment by holiman** [comment]
Are we talking about consensus-testing, or just 'can I crash this thing?'. Basically, AFL-fuzz it like solidity/solfuzz or make something a bit more clever, like differential fuzzing against geth/parity ? 

Cc @guidovvranken

**Comment by axic** [comment]
For now 
> can I crash this thing?

In 2-3 weeks (more realistically after devcon) we can move into consensus testing by running both Hera and Wagon. But first Wagon support needs to be finished in geth @gballet.

**Comment by axic** [comment]
A quick and dirty way to crash on the desired exceptions is to add `abort()` into these three:
https://github.com/ewasm/hera/blob/master/src/hera.cpp#L371-L380

- `(InternalErrorException)`
- `(std::exception)`
- `(...)`

**Comment by holiman** [comment]
Point me to a binary, build instructions, LMK what types of input it takes, and I'll get started :)

**Comment by axic** [comment]
Use this branch: https://github.com/ewasm/hera/pull/392

Build with:
```
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=ON ..
make
```

Run with `aleth --vm ~/build/src/libhera.so --singlenet Byzantium <code goes here>`.
