### ISSUE TITLE
Hera doesn't seem to create the contract in a revert

### ISSUE THREAD

**Issue by gballet** [ewasm/hera#457]
This is the debug output of `testeth` + `hera` v0.2.0 when running `createCodeWithRevert`:

```
DEBUG 11-21 18:43:33 testeth overlaydb Closing state DB
INFO  11-21 18:43:33 testeth state  trNetID: Byzantium
trDataInd: 0 tdGasInd: 0 trValInd: 0

INFO  11-21 18:43:33 testeth state  
2adc25665018aa1fe0e6bc666dac8fc2697ff9ba
'balance' : ['0x00', '+=', '0x013634']
'balance' : ['0x00', '->', '0x013634']
'newlyCreated' : ['true']

a94f5374fce5edbc8e2a8697c15331677e6ebf0b
'balance' : ['0x174876e800', '+=', '0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffff953040']
'balance' : ['0x17480c1840', '+=', '0x69998c']
'balance' : ['0x174876e800', '->', '0x174875b1cc']
'nonce' : ['0x04', '->', '0x05']

deadbeef00000000000000000000000000000000
'nonce' : ['0x00', '->', '0x01']
'storage' : ['0x00 : 0x00', '->', '0x00 : 0x0200000000000000000000000000000000000000000000000000000000000000']

DEBUG 11-21 18:43:33 testeth overlaydb Closing state DB
DEBUG 11-21 18:43:33 testeth overlaydb Closing state DB
```

One can already see that no newly created contract with code exists. There should be a line saying something like `'code' : ['0x', '->', '0x...']`

`wagon` fails the test as a new account is effectively created:

```
f2048c36a5536fea3bc71d49ed59f2c65c546eea:{0 1 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421 50cc9609ed13c878caf0b7ac27b34f56c318680963224914c6ea863d460f8a7f beef map[]}]}
```

**Comment by lrettig** [comment]
The [createCodeWithRevert](https://github.com/ewasm/tests/blob/wasm-tests/src/GeneralStateTestsFiller/stEWASMTests/createCodeWithRevertFiller.yml) test does not appear to test for the existence or non-existence of the new account. Am I missing something? What's the expected behavior here?

> wagon fails the test as a new account is effectively created

Are you suggesting that the wagon behavior is the expected behavior and the hera behavior is wrong?

**Comment by gballet** [comment]
> The [createCodeWithRevert](https://github.com/ewasm/tests/blob/wasm-tests/src/GeneralStateTestsFiller/stEWASMTests/createCodeWithRevertFiller.yml) test does not appear to test for the existence or non-existence of the new account. Am I missing something? What's the expected behavior here?

indeed it doesn't test for it. That's one of the problems.

  * The name of the test is "createWithRevert" and it *does* tries to create a contract.
  * Contract creation fails in hera, and not with wagon. I'm not sure why it fails in hera, as it goes through the same steps of gas consumption as wagon does.

> Are you suggesting that the wagon behavior is the expected behavior and the hera behavior is wrong?

yes. If the test is called "createwithrevert" then it seems to me that it should create a contract by creating a revert. This is exactly what happens with wagon. If that's indeed not the expected behavior (which I think it should be), the name of that test should be changed to reflect why hera fails.

**Comment by gballet** [comment]
@axic any opinion ?

**Comment by lrettig** [comment]
I don't have an opinion about expected behavior here but I'm not sure that we've used a consistent naming convention in all of the tests, so the names of some may be misleading or even "backwards" - I've tried to remedy that recently by including a comment in the first line of the filler file that says what the test is supposed to do.

**Comment by axic** [comment]
> indeed it doesn't test for it. That's one of the problems, the others being:

It should test for it and it shouldn't be created.

The main goal of this test is that a "constructor" bytecode when doing a revert it should be considered as a failure and no account should be created.

**Comment by gballet** [comment]
Ok, got confused by the title. Got fixed in wagon.
