### ISSUE TITLE
Support wasmer as VM

### ISSUE THREAD

**Issue by axic** [ewasm/hera#459]

**Comment by speqtr** [comment]
Hi,

Is some already working on this issue? If not then I'm willing to implement this task 🙂

Any details/notes/suggestions/guidance I should know about before I start working on this task?

cc @axic

**Comment by poemm** [comment]
Wasmer has similarities to https://github.com/CraneStation/wasmtime .

Would need support for calls between Hera C++ functions and Wasmer Rust functions. If Rust supports C calling conventions, then maybe `extern "C"` in Hera will prevent the name mangling and to use C calling conventions. Also need to share memory pointers across languages. And might need to catch each other's exceptions.

Might be easier to rewrite hera in Rust.

**Comment by axic** [comment]
Given recent progress on Rust bindings for EVMC, this seems to be better suited for https://github.com/ewasm/hera.rs

Closing it here.
