### ISSUE TITLE
-DHERA_BENCHMARKING=ON

### ISSUE THREAD

**Issue by poemm** [ewasm/hera#485]
Can we add flag `-DHERA_BENCHMARKING=ON` when compiling Hera, and include the following code in each engine's interface to print benchmarking data? @chfast 

```
#if HERA_BENCHMARKING
#include <fstream>      // std::fstream
#include <time.h>       // clock_t, clock
#endif

...

#if HERA_BENCHMARKING
clock_t t = clock();
#endif

...parse/validate/compile...

#if HERA_BENCHMARKING
t = clock() - t;
std::fstream fs;
fs.open ("runtime_data_wavm_compile.csv", std::fstream::out | std::fstream::app);
fs << ", " << ((float)t)/CLOCKS_PER_SEC;
fs.close();
#endif

...

#if HERA_BENCHMARKING
clock_t t2 = clock();
#endif

...invoke main...

#if HERA_BENCHMARKING
t2 = clock() - t2;
std::fstream fs2;
fs2.open ("runtime_data_wavm_invoke.csv", std::fstream::out | std::fstream::app);
fs2 << ", " << ((float)t2)/CLOCKS_PER_SEC;
fs2.close();
#endif
```

**Comment by chfast** [comment]
Is this necessary to dump it to a file?

**Comment by poemm** [comment]
It would be nice if the runtimes were eventually dumped to a file so that we can compare them.

**Comment by axic** [comment]
Having a prefix, like `[hera benchmark]` and displaying the lines on `stdout` would allow grepping fori t.

**Comment by chfast** [comment]
I can do both, but I will start with the standard output first.
I also prefer using runtime flags than build flags. Unless strong objection the first version will introduce `benchmark` EVMC-like option.

**Comment by axic** [comment]
I think the runtime flag could have a large speed penalty so would prefer the build flag for this instance.

**Comment by chfast** [comment]
> could have a large speed penalty

Unverified claim. I claim there will be 0 speed penalty.

**Comment by axic** [comment]
So you claim that having runtime branches around all the different EEI methods provides 0 speed penalty?

**Comment by poemm** [comment]
The reason that I proposed a preprocessor flag is because I expected a speed penalty from system calls for `clock()` and writing data, each of which require a context switch to kernel mode, executing the system call, possibly doing some unrelated scheduled kernel work, and context switching back, this is not to speak of TLB misses or cache misses. This speed penalty may be negligible for long-running precompiles, but may be non-negligible for short contracts. I think that @axic 's concerns about speed penalties are consistent with other design decisions of hera.

If this issue remains unresolved, then I will submit a pull request for the above code once I become blocked on this, probably on Tuesday.
