### ISSUE TITLE
Implement the debug namespace

### ISSUE THREAD

**Issue by axic** [ewasm/hera#70]
Should add the same methods as ewasm-kernel: https://github.com/ewasm/ewasm-kernel/blob/master/debugInterface.js

- `print32(value: i32)`
- `print64(value: i64)`
- `printMem(offset: i32, len: i32)` - print memory segment as printable characters
- `printMemHex(offset: i32, len: i32)` - print memory segment as a hex

Should only be enabled in debug mode.

**Comment by lrettig** [comment]
Already partially working. What do `print32` and `print64` do? Just print the value as hex? As printable chars?

**Comment by axic** [comment]
I think they could just print both printable and hex at the same time.
