### ISSUE TITLE
Charge gas for each interface method properly

### ISSUE THREAD

**Issue by axic** [ewasm/hera#74]
See https://github.com/ethereum/evmjit/blob/develop/libevmjit/JIT.h#L60-L90 for some numbers.

**Comment by jakelang** [comment]
Working branch: #86

**Comment by jakelang** [comment]
TODO list:
- [] useGas
- [] getAddress
- [] getBalance
- [] getBlockHash
- [] call
- [] callDataCopy
- [] getCallDataSize
- [] callCode
- [] callDelegate
- [] callStatic
- [] storageStore
- [] storageLoad
- [] getCaller
- [] getCallValue
- [] codeCopy
- [] getCodeSize
- [] getBlockCoinbase
- [] create
- [] getBlockDifficulty
- [] externalCodeCopy
- [] getExternalCodeSize
- [] getGasLeft
- [] getBlockGasLimit
- [] getTxGasPrice
- [] log
- [] getBlockNumber
- [] getTxOrigin
- [] return
- [] revert
- [] selfDestruct
- [] getBlockTimestamp
- [] returnDataCopy
- [] returnDataSize
